[package]
name = "style_traits"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
repository = "https://github.com/servo/stylo"
publish = false

[lib]
name = "style_traits"
path = "lib.rs"

[features]
servo = ["servo_atoms", "cssparser/serde", "webrender_api", "url", "euclid/serde"]
gecko = []

[dependencies]
app_units = "0.7"
bitflags = "2"
cssparser = "0.34"
euclid = "0.22"
lazy_static = "1"
malloc_size_of = { path = "../malloc_size_of" }
malloc_size_of_derive = "0.1"
selectors = { path = "../selectors" }
serde = "1.0"
servo_arc = { path = "../servo_arc", version = "0.4", package = "stylo_arc" }
servo_atoms = { version = "0.1", path = "../atoms", package = "stylo_atoms", optional = true }
thin-vec = "0.2"
to_shmem = { version = "0.1", path = "../to_shmem", package = "stylo_to_shmem" }
to_shmem_derive = { version = "0.1", path = "../to_shmem_derive", package = "stylo_to_shmem_derive" }
url = { version = "2.5", optional = true }
webrender_api = { git = "https://github.com/servo/webrender", branch = "0.65", optional = true }
