[package]
name = "stylo_malloc_size_of"
version = "0.1.1"
authors = ["The Servo Project Developers"]
documentation = "https://docs.rs/stylo_malloc_size_of/"
description = "Support crate for Stylo CSS engine"
repository = "https://github.com/servo/stylo"
keywords = ["css", "style"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
path = "lib.rs"

[features]
gecko = ["thin-vec/gecko-ffi"]
servo = ["string_cache"]

[dependencies]
app_units = "0.7"
cssparser = "0.34"
euclid = "0.22"
selectors = { version = "0.26", path = "../selectors", package = "stylo_selectors" }
servo_arc = { path = "../servo_arc", version = "0.4", package = "stylo_arc" }
smallbitvec = "2.3.0"
smallvec = "1.13"
string_cache = { version = "0.8", optional = true }
thin-vec = { version = "0.2.13" }
void = "1.0.2"
